name: deimos-gui
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - colorcet
  - holoviews
  - panel
  - xarray
  - hvplot
  - datashader
  - pandas
  - playwright
  - pytest
  - pytest-playwright
  - dask
  - pip
  - pip:
      - git+https://github.com/pnnl/deimos
      - git+https://github.com/pymzml/pymzML.git@b536dc48429e442bb637ca277cf16a14e2047c2d
